name: Code Quality Checks

on:
  push:

jobs:
  linting:
        - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install ruff

      - name: Code Linting
        if: always()
        run: ruff check qrcode

      - name: Code Formatting
        if: always()
        run: ruff format --check qrcode
